services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: "rinha_backend"
      MYSQL_USER: "rinha"
      MYSQL_PASSWORD: "backend"
      MYSQL_ROOT_PASSWORD: "backend"
    healthcheck:
      test: mysql -h db -u rinha -pbackend rinha_backend -e "SELECT count(*) FROM rinha_backend.Cliente;"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "3306:3306"
    expose:
      - "3306"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "300mb"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api01: &api
    image: droderuan/node-rinha-backend-2024
    hostname: api01
    restart: always
    command: npm run start:prod
    ports:
      - "8081:3333"
    environment:
      DB_HOST: "db"
      DB_POOL: 15
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100mb"
  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:3333"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
