version: "3.5"

services:
  api01: &api
    image: caiquereinhold/caique:rinha-backend
    hostname: api01
    command: "uvicorn uvicorn_raw:app --host 0.0.0.0 --port 8081 --workers 3 --loop uvloop --log-level error"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "140MB"
  api02:
    <<: *api
    hostname: api02
    command: "uvicorn uvicorn_raw:app --host 0.0.0.0 --port 8082 --workers 3 --loop uvloop --log-level error"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "260MB"
networks:
  default:
    driver: bridge
