version: "3.5"

services:
  api01: &api
    image: brunolipea/rinha-2024-q1-adonisjs
    env_file:
      - .env.production.local
    # ports:
    #   - "3001:3333"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    command: node ./bin/server.js
    # ports:
    #   - "3002:3333"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    # ports:
    #   - "5433:5432"
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"
