version: "3.5"

services:
  api01: &api
    image: rigotti/rinha-de-backend-2024
    hostname: api01
    environment:
      DATABASE_URL: postgres://admin:123@db:5432/rinha
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -N 50 -c shared_buffers=256MB
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "470MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
