version: '3.5'

services:
  api:
    image: dreamagici4n/rinha-2024:1.2
    hostname: api
    environment:
      - MONGO_URI=mongodb://db:27017/rinha
      - PORT=3000
    depends_on:
      - db
    tty: true
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: mongo:7.0.5-jammy
    hostname: db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=rinha
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
    