version: '3'
services:

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "Pa55w0rd2019"
      MYSQL_DATABASE: "ContaBancaria"
    ports:
      - "3306:3306"
    volumes:
      - ./ScriptCreateDatabase.sql:/docker-entrypoint-initdb.d/ScriptCreateDatabase.sql
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "350MB"

  api01: &api
    image: marisouzas2/bancoapi:latest
    hostname: api01
    ports:
      - "5000:80"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "75MB"

  api02: 
    <<: *api
    hostname: api02
    ports:
      - "5001:80"
    depends_on:
      - api01
    
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"
